# Generated by Django 5.1.15 on 2026-07-03 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('country', models.CharField(default='RO', max_length=2)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('line1', models.CharField(max_length=255)),
                ('line2', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'addresses',
            },
        ),
        migrations.CreateModel(
            name='CartUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.SlugField(help_text='Matches the ProductInputField.key.')),
                ('file', models.FileField(upload_to='cart_uploads/%Y/%m/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('accepts_marketing', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('invoice', 'Invoice (factură)'), ('storno', 'Storno / credit note')], default='invoice', max_length=20)),
                ('number', models.PositiveIntegerField()),
                ('issued_at', models.DateTimeField()),
                ('currency', models.CharField(default='RON', max_length=3)),
                ('net_amount', models.PositiveIntegerField()),
                ('vat_amount', models.PositiveIntegerField()),
                ('gross_amount', models.PositiveIntegerField()),
                ('snapshot', models.JSONField(default=dict)),
                ('efactura_status', models.CharField(choices=[('not_sent', 'Not sent'), ('queued', 'Queued for submission'), ('sent', 'Sent to ANAF'), ('accepted', 'Accepted by ANAF'), ('rejected', 'Rejected by ANAF')], default='not_sent', max_length=20)),
                ('efactura_upload_id', models.CharField(blank=True, max_length=100)),
                ('efactura_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'invoice series',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_payment', 'Pending payment'), ('paid', 'Paid'), ('in_production', 'In production'), ('ready_to_ship', 'Ready to ship'), ('shipped', 'Shipped'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='draft', max_length=30)),
                ('currency', models.CharField(default='RON', max_length=3)),
                ('subtotal_net_amount', models.PositiveIntegerField(default=0)),
                ('subtotal_amount', models.PositiveIntegerField(default=0)),
                ('shipping_amount', models.PositiveIntegerField(default=0)),
                ('discount_amount', models.PositiveIntegerField(default=0)),
                ('vat_amount', models.PositiveIntegerField(default=0)),
                ('total_amount', models.PositiveIntegerField(default=0)),
                ('vat_enabled_snapshot', models.BooleanField(default=False)),
                ('vat_breakdown', models.JSONField(blank=True, default=dict, help_text="e.g. {'1900': {'net': ..., 'vat': ...}} keyed by rate_bp.")),
                ('customer_notes', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('placed_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=255)),
                ('product_slug', models.SlugField(blank=True, max_length=255)),
                ('variant_name', models.CharField(blank=True, max_length=100)),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price_amount', models.PositiveIntegerField()),
                ('line_total_amount', models.PositiveIntegerField()),
                ('unit_net_amount', models.PositiveIntegerField(default=0)),
                ('line_net_amount', models.PositiveIntegerField(default=0)),
                ('line_vat_amount', models.PositiveIntegerField(default=0)),
                ('vat_rate_bp', models.PositiveIntegerField(default=0)),
                ('vat_is_exempt', models.BooleanField(default=True)),
                ('vat_legal_mention', models.CharField(blank=True, max_length=255)),
                ('currency', models.CharField(default='RON', max_length=3)),
                ('selected_options_snapshot', models.JSONField(blank=True, default=list)),
                ('inputs_snapshot', models.JSONField(blank=True, default=dict)),
                ('price_breakdown', models.JSONField(blank=True, default=dict)),
                ('production_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaxConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vat_enabled', models.BooleanField(default=False, help_text='OFF = neplătitor de TVA. Prices charged as-is, 0 VAT on invoices.')),
                ('prices_include_vat', models.BooleanField(default=True, help_text='When VAT is enabled: True = base_price_amount is gross (VAT-inclusive), extract VAT out of it. False = base price is net, add VAT on top.')),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('cui', models.CharField(blank=True, help_text='CUI / CIF.', max_length=20)),
                ('reg_com', models.CharField(blank=True, help_text='Nr. Reg. Com.', max_length=50)),
                ('fiscal_address', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'tax configuration',
                'verbose_name_plural': 'tax configuration',
            },
        ),
        migrations.CreateModel(
            name='VatRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rate_bp', models.PositiveIntegerField(help_text='Rate in basis points. 1900 = 19%. 900 = 9%. 0 = exempt/0%.')),
                ('is_exempt', models.BooleanField(default=False, help_text='True for neplătitor / scutit — legal mention, not a %.')),
                ('legal_mention', models.CharField(blank=True, help_text="Printed on invoice, e.g. 'Neplătitor de TVA' or 'Scutit conform art. ...'.", max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=100)),
                ('currency', models.CharField(default='RON', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('inputs', models.JSONField(blank=True, default=dict)),
                ('price_breakdown', models.JSONField(blank=True, default=dict)),
                ('unit_price_amount', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='RON', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.cart')),
            ],
        ),
    ]
