# Generated by Django 5.1.15 on 2026-10-01 09:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0001_initial'),
        ('orders', '0003_order_payment_resume_email_sent_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('enabled', models.BooleanField(default=True)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='address',
            name='cui',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='address',
            name='is_company',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='address',
            name='reg_com',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='pdf_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='awb',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='courier',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='taxconfig',
            name='bank',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='taxconfig',
            name='default_invoice_series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orders.invoiceseries'),
        ),
        migrations.AddField(
            model_name='taxconfig',
            name='iban',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='taxconfig',
            name='invoice_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='taxconfig',
            name='invoice_footer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='taxconfig',
            name='invoice_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_library.mediaasset'),
        ),
        migrations.AddField(
            model_name='taxconfig',
            name='invoice_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='taxconfig',
            name='payment_term_days',
            field=models.PositiveSmallIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='taxconfig',
            name='share_capital',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='taxconfig',
            name='swift',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.CreateModel(
            name='NotificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_notifications_enabled', models.BooleanField(default=True)),
                ('order_recipients', models.JSONField(blank=True, default=list)),
                ('sender_name', models.CharField(default='Ave Letter', max_length=100)),
                ('reply_to', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('pk', 1)), name='single_notification_config')],
            },
        ),
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40)),
                ('from_status', models.CharField(blank=True, max_length=30)),
                ('to_status', models.CharField(blank=True, max_length=30)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='OutgoingEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_key', models.CharField(max_length=40)),
                ('idempotency_key', models.CharField(max_length=200, unique=True)),
                ('recipient', models.EmailField(max_length=254)),
                ('from_email', models.CharField(max_length=255)),
                ('reply_to', models.EmailField(blank=True, max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('html_body', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'În așteptare'), ('sending', 'Se trimite'), ('sent', 'Trimis'), ('failed', 'Eșuat'), ('skipped', 'Omis'), ('uncertain', 'Rezultat necunoscut')], db_index=True, default='pending', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='orders.orderevent')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emails', to='orders.invoice')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
