# Generated by Django 5.1.15 on 2026-07-03 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_library', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_library.mediaasset')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shop.productcategory')),
            ],
            options={
                'verbose_name_plural': 'product categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('seo_title', models.CharField(blank=True, max_length=70)),
                ('seo_description', models.CharField(blank=True, max_length=160)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('product_type', models.CharField(choices=[('standard', 'Standard product'), ('text_by_page', 'Text priced by page'), ('ornament', 'Short text ornament'), ('custom_quote', 'Custom quote')], default='standard', max_length=30)),
                ('short_description', models.TextField(blank=True)),
                ('description', models.JSONField(blank=True, default=dict)),
                ('description_text', models.TextField(blank=True)),
                ('base_price_amount', models.PositiveIntegerField(default=0, help_text='Base price in bani. Example: 5000 = 50 RON.')),
                ('currency', models.CharField(default='RON', max_length=3)),
                ('is_featured', models.BooleanField(default=False)),
                ('requires_manual_approval', models.BooleanField(default=False, help_text='Useful for complex custom work.')),
                ('production_time_min_days', models.PositiveIntegerField(default=3)),
                ('production_time_max_days', models.PositiveIntegerField(default=10)),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_library.mediaasset')),
                ('vat_rate', models.ForeignKey(blank=True, help_text='If empty, the active site default VAT rate applies.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='orders.vatrate')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.productcategory')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_text_override', models.CharField(blank=True, max_length=500)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_library.mediaasset')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
            options={
                'ordering': ['sort_order'],
                'unique_together': {('product', 'asset')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='gallery',
            field=models.ManyToManyField(blank=True, related_name='products', through='shop.ProductImage', to='media_library.mediaasset'),
        ),
        migrations.CreateModel(
            name='ProductInputField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Stable API key, e.g. message_text, ornament_words.')),
                ('label', models.CharField(max_length=120)),
                ('field_type', models.CharField(choices=[('short_text', 'Short text'), ('long_text', 'Long text'), ('number', 'Number'), ('date', 'Date'), ('email', 'Email'), ('file', 'File upload'), ('boolean', 'Boolean')], max_length=30)),
                ('required', models.BooleanField(default=False)),
                ('help_text', models.TextField(blank=True)),
                ('placeholder', models.CharField(blank=True, max_length=255)),
                ('min_chars', models.PositiveIntegerField(blank=True, null=True)),
                ('max_chars', models.PositiveIntegerField(blank=True, null=True)),
                ('min_words', models.PositiveIntegerField(blank=True, null=True)),
                ('max_words', models.PositiveIntegerField(blank=True, null=True)),
                ('validation_regex', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_fields', to='shop.product')),
            ],
            options={
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='ProductOptionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('display_type', models.CharField(choices=[('select', 'Select'), ('radio', 'Radio'), ('color', 'Color swatches'), ('checkbox', 'Checkboxes')], default='select', max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('min_selections', models.PositiveIntegerField(default=0)),
                ('max_selections', models.PositiveIntegerField(default=1)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_groups', to='shop.product')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.SlugField()),
                ('price_delta_amount', models.IntegerField(default=0, help_text='Can be positive or negative. In bani.')),
                ('color_hex', models.CharField(blank=True, help_text='For color options, e.g. #C9A227.', max_length=7)),
                ('extra_production_days', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_library.mediaasset')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='shop.productoptiongroup')),
            ],
            options={
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sku', models.CharField(blank=True, default=None, max_length=100, null=True, unique=True)),
                ('price_override_amount', models.PositiveIntegerField(blank=True, help_text='If empty, product base price is used.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('track_stock', models.BooleanField(default=False)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='shop.product')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TextByPagePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_field_key', models.SlugField(default='message_text', help_text='Which ProductInputField contains the priced text.')),
                ('words_per_page', models.PositiveIntegerField(default=100)),
                ('price_per_page_amount', models.PositiveIntegerField(help_text='In bani.')),
                ('minimum_pages', models.PositiveIntegerField(default=1)),
                ('maximum_pages', models.PositiveIntegerField(blank=True, null=True)),
                ('setup_fee_amount', models.PositiveIntegerField(default=0)),
                ('round_up', models.BooleanField(default=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='text_pricing', to='shop.product')),
            ],
            options={
                'verbose_name_plural': 'text-by-page pricing',
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'product_type'], name='shop_produc_status_b9ec4e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_featured', 'status'], name='shop_produc_is_feat_e6daf9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productinputfield',
            unique_together={('product', 'key')},
        ),
        migrations.AlterUniqueTogether(
            name='productoptiongroup',
            unique_together={('product', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='productoption',
            unique_together={('group', 'value')},
        ),
    ]
