# Generated by Django 5.1.15 on 2026-07-03 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Ave Letter', max_length=100)),
                ('domain', models.CharField(default='aveletter.ro', max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('instagram_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('default_seo_title', models.CharField(blank=True, max_length=70)),
                ('default_seo_description', models.CharField(blank=True, max_length=160)),
                ('announcement_enabled', models.BooleanField(default=False)),
                ('announcement_text', models.CharField(blank=True, max_length=255)),
                ('free_shipping_threshold_amount', models.PositiveIntegerField(blank=True, help_text='In bani. Example: 30000 = 300 RON.', null=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_library.mediaasset')),
            ],
            options={
                'verbose_name': 'site configuration',
                'verbose_name_plural': 'site configuration',
            },
        ),
    ]
